import React from "react";
import { useGLTF } from "@react-three/drei";
import { useCharacterAnimations } from "../globales/CharacterAnimations";

export function Piano(props) {
  const { nodes, materials } = useGLTF(
    "/assets/models/piano/piano_with_chair.glb"
  );
  const { setClicPiano, setClicNext, setMostrar, avatar } =
    useCharacterAnimations();

  const handleClick = () => {
    if (avatar.current.position.x <= 1.41) {
      setClicPiano(true);
      setClicNext(false);
      setMostrar(true);
    }
  };

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={10}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LayerPIANO_B_KEYS_Paint_Gloss_Black_0.geometry}
            material={materials.Paint_Gloss_Black}
            position={[-0.013, -0.864, 0.843]}
            onClick={handleClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LayerPIANO_W_KEYS_Paint_Gloss_White_0.geometry}
            material={materials.Paint_Gloss_White}
            position={[0, -0.907, 0.82]}
            onClick={handleClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LayerPIANO_MAIN_Cherry_0.geometry}
            material={materials.Cherry}
            position={[0, 0.238, 0.596]}
            onClick={handleClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LayerPIANO_BRASS_Copper_Rough_0.geometry}
            material={materials.Copper_Rough}
            position={[0, 0.239, 0.047]}
            onClick={handleClick}
          />
        </group>
        <group
          position={[-0.55, -14.406, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          onClick={handleClick}
        >
          <group position={[0, 0, 19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_1"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_0}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_2"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_1}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_3"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_2}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_4"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_3}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_5"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_4}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_6"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_5}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_7"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_6}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_8"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_7}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_9"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_8}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_10"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_9}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_1"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_0}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_2"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_1}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_3"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_2}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_4"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_3}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_5"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_4}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_6"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_5}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_7"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_6}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Steel_#1_0"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Steel_1}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Steel_#1_0_1"].geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Steel_1_0}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_8"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_7}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_9"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_8}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_10"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_9}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_11"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_10}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Material_#1_0_12"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Material_1_11}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_11"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_10}
              onClick={handleClick}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes["uploads_files_147002_Piano_chair_Cherry_#1_0_12"]
                  .geometry
              }
              scale-y={1.1}
              position-z={-100}
              material={materials.Cherry_1_11}
              onClick={handleClick}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/piano/piano_with_chair.glb");
